packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Node.js types
  "@types/node": "^20.11.24"

  # Core dependencies
  "express": "^4.18.2"
  "@types/express": "^4.17.21"
  "cors": "^2.8.5"
  "@types/cors": "^2.8.17"

  # CloudEvents
  "cloudevents": "^7.0.2"

  # Message Queue
  "amqplib": "^0.10.3"
  "@types/amqplib": "^0.10.4"

  # Validation
  "zod": "^3.22.4"

  # Logging
  "pino": "^8.19.0"
  "pino-pretty": "^10.3.1"

  # Tracing
  "@opentelemetry/api": "^1.8.0"
  "@opentelemetry/sdk-node": "^0.49.1"
  "@opentelemetry/auto-instrumentations-node": "^0.42.0"

  # Configuration
  "dotenv": "^16.4.5"

  # HTTP Client
  "axios": "^1.6.7"

  # Testing
  "jest": "^29.7.0"
  "@types/jest": "^29.5.12"
  "ts-jest": "^29.1.2"
  "supertest": "^6.3.4"
  "@types/supertest": "^6.0.2"
  "cucumber": "^10.3.1"
  "@cucumber/cucumber": "^10.3.1"

  # Build tools
  "typescript": "^5.3.3"
  "ts-node": "^10.9.2"
  "tsx": "^4.7.1"
  "nodemon": "^3.1.0"

  # Linting
  "eslint": "^8.57.0"
  "@typescript-eslint/eslint-plugin": "^7.1.1"
  "@typescript-eslint/parser": "^7.1.1"
  "prettier": "^3.2.5"

  # Utilities
  "uuid": "^9.0.1"
  "@types/uuid": "^9.0.8"