global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js applications metrics
  - job_name: 'app-service'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'

  - job_name: 'interop-layer'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'

  - job_name: 'mediator-services'
    static_configs:
      - targets: ['host.docker.internal:3003']
    metrics_path: '/metrics'

  - job_name: 'webhook-services'
    static_configs:
      - targets: ['host.docker.internal:3004']
    metrics_path: '/metrics'

  - job_name: 'client-service'
    static_configs:
      - targets: ['host.docker.internal:3005']
    metrics_path: '/metrics'

  # Infrastructure metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']